project:
  type: website
  title: Cyberinfrastructure for Efficient Ecological Forecasting
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs

format:
  html:
    theme: "zephyr"
    toc: true
    from: markdown+emoji
    bibliography: references.bibtex
    lightbox: auto

website:
  favicon: images/EFI_Logo-1.jpg
  site-url: https://projects.ecoforecast.org/efi-ci-workshop-2024/
  repo-url: https://github.com/eco4cast/efi-ci-workshop-2024
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    left:
      - sidebar:workshop-summary
      - sidebar:ci-handbook
      - sidebar:reference
    right: 
      - icon: github
        href: https://github.com/eco4cast/efi-ci-workshop-2024
      
  sidebar:
    - id: workshop-summary
      title: "Workshop Summary"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - workshopsummary/index.qmd
        - workshopsummary/summary.qmd
        - workshopsummary/brief.qmd
        - workshopsummary/report.qmd

    - id: ci-handbook
      title: "CI Handbook"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - ci_handbook/index.qmd
        - ci_handbook/model-output-standards.qmd
        - ci_handbook/design_justice.qmd
        - ci_handbook/workflow_design.qmd
        - ci_handbook/modularity.qmd 
        - ci_handbook/data_standards.qmd
        - ci_handbook/cloud_computing.qmd 
        - ci_handbook/continuous_integration.qmd
        - ci_handbook/example.qmd

    - id: reference
      title: "Reference"
      contents:
        - reference/index.qmd
        - reference/EFI_CI_reference.qmd
        - reference/participants.qmd

