project:
  type: website
  title: Cyberinfrastructure for Efficient Ecological Forecasting
  render:
    - "*.qmd"
    - "*.md"

format:
  html:
    theme: "zephyr"
    toc: true
    from: markdown+emoji
    bibliography: references.bibtex
    lightbox: auto

website:
  favicon: images/EFI_Logo-1.jpg
  repo-url: https://github.com/eco4cast/efi-ci-workshop-2024
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: true
    left:
      - sidebar:workshop-summary
      - sidebar:reference

  sidebar:
    - id: workshop-summary
      title: "Workshop Summary"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - workshopsummary/summary.qmd
        - workshopsummary/brief.qmd

    - id: reference
      title: "Reference"
      contents:
        - reference/EFI_CI_reference.qmd

# Deployment settings
project:
  output-dir: _site  # Where rendered site files go
  preview: true  # Use Quarto's preview function for local development

