name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - run: git config --system --add safe.directory '*'

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        set-safe-directory: '*'

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render
      run: |
        quarto render
        
    - name: Publish
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout gh-pages || git checkout --orphan gh-pages  # Checkout or create the gh-pages branch
        cp -r docs/* .  # Copy files to the root directory
        git add .
        git commit -a -m "update pages" || echo "nothing to commit"  # Commit changes
        git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY} gh-pages  # Push to gh-pages

        